"""add status column to journal_entries

Revision ID: dc781efc8da7
Revises: 42ed0bbe28b6
Create Date: 2025-12-10 13:04:04.105223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc781efc8da7'
down_revision: Union[str, None] = '42ed0bbe28b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE processingstatus AS ENUM ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED')")
    op.add_column('journal_entries', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='processingstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'status')
    op.execute("DROP TYPE processingstatus")
    # ### end Alembic commands ###
