FROM cosdataio/cosdata:latest

# Copy init script and keys file
COPY infra/cosdata-init.sh /entrypoint.sh
COPY infra/cosdata-keys.txt /root/.cosdata/keys.txt
RUN chmod +x /entrypoint.sh

EXPOSE 8443 50051

# Use the init script as entrypoint
ENTRYPOINT ["/entrypoint.sh"]
